#!/usr/bin/env python3
"""
065_select_best_windows.py
--------------------------
Scans multiclass performance CSV files across multiple epoch time windows 
(e.g., 0-300ms, 300-600ms, 600-900ms, 0-400ms, 400-800ms, 0-800ms), aggregates 
results across all windows, bands, feature modes, and model types, and selects 
the peak-performing configuration for each [Task, Condition] pair.

Output Files:
- outputs/multiclass_best_results_all_conditions.csv
  (Peak model for each [Task, Condition] combination, tagged with its specific winning window)
- outputs/multiclass_best_overall_by_task.csv
  (Single best model overall for each Task across all conditions and windows)

This bridge script prepares the optimized time-window dataset for downstream 
evaluation by Script 07 (Permutation Testing), Script 08 (Survived Features), 
and Script 09 (Excel Summary Compilation).
"""

import os
import sys
import glob
import re
import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# 1. Set paths
# ============================================================

BASE_DIR = Path(__file__).resolve().parent
if BASE_DIR.name == "scripts":
    BASE_DIR = BASE_DIR.parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(exist_ok=True)
INPUT_DIR = OUTPUT_DIR
base_path = Path(DATA_DIR).expanduser()

ACTIVE_TASKS = [
    "Age_Group",
    "Language_Tonal",
    "Language",
    "Age_Child_Language_Tonal",
    "Age_Child_Language"
]

def extract_window_from_filename(filename):
    """
    Extracts time window string from file patterns like:
    - multiclass_results_all_conditions_0-300ms.csv -> 0-300ms
    - multiclass_results_all_conditions_300_600.csv -> 300-600ms
    - multiclass_results_0_400.csv -> 0-400ms
    """
    base = os.path.basename(filename)
    match = re.search(r'(\d+)[\-_](\d+)(?:ms)?', base)
    if match:
        start, end = match.group(1), match.group(2)
        return f"{start}-{end}ms"
    return None

def main():
    print("=== Step 06.5: Time-Window Optimization & Best Model Selection ===")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # 2. Locate all multiclass results CSVs
    search_patterns = [
        os.path.join(INPUT_DIR, "multiclass_results_all_conditions*.csv"),
        os.path.join(INPUT_DIR, "multiclass_results_*.csv"),
        os.path.join(INPUT_DIR, "*multiclass_results*.csv")
    ]
    
    found_files = set()
    for pattern in search_patterns:
        for f in glob.glob(pattern):
            # Skip output files generated by this script or old summary files
            if not any(excluded in os.path.basename(f) for excluded in ["best_", "permutation", "survived", "summary"]):
                found_files.add(f)
                
    found_files = sorted(list(found_files))
    
    if not found_files:
        print(f"Warning: No multiclass result CSV files found in '{INPUT_DIR}'.")
        print("Searching fallback directory '/workspace/artifacts/'...")
        fallback_files = glob.glob("/workspace/artifacts/*multiclass*results*.csv")
        found_files = sorted([f for f in fallback_files if "best" not in os.path.basename(f)])

    if not found_files:
        print("Error: No valid result CSV files found to process.")
        sys.exit(1)

    print(f"Found {len(found_files)} performance files to scan:")
    for f in found_files:
        print(f"  - {f}")

    # 3. Aggregate and harmonize all results DataFrames
    dfs = []
    for fpath in found_files:
        try:
            df = pd.read_csv(fpath)
            if df.empty:
                continue
                
            # Deduce or standardize Window column
            if "Window" not in df.columns or df["Window"].isna().all():
                inferred_window = extract_window_from_filename(fpath)
                if inferred_window:
                    df["Window"] = inferred_window
                else:
                    df["Window"] = "0-800ms (Full)"
                    
            dfs.append(df)
        except Exception as e:
            print(f"Warning: Could not read '{fpath}': {e}")

    if not dfs:
        print("Error: No readable data extracted from performance files.")
        sys.exit(1)

    combined_df = pd.concat(dfs, ignore_index=True)
    
    # Clean duplicates & obsolete tasks
    if "Task" in combined_df.columns:
        combined_df = combined_df[combined_df["Task"].isin(ACTIVE_TASKS)]
        
    # Ensure AUC_mean is float
    combined_df["AUC_mean"] = pd.to_numeric(combined_df["AUC_mean"], errors="coerce")
    combined_df = combined_df.dropna(subset=["AUC_mean"])

    print(f"\nTotal evaluated configurations loaded: {len(combined_df)}")
    print(f"Tasks represented: {combined_df['Task'].unique().tolist() if 'Task' in combined_df.columns else 'N/A'}")
    print(f"Windows scanned: {combined_df['Window'].unique().tolist()}")

    # 4. Group by [Task, Condition] and select row with maximum AUC_mean
    group_cols = [c for c in ["Task", "Condition"] if c in combined_df.columns]
    
    if not group_cols:
        print("Error: Missing required 'Task' or 'Condition' columns.")
        sys.exit(1)

    # Sort descending by AUC_mean
    sorted_df = combined_df.sort_values(by="AUC_mean", ascending=False)
    
    # Best per [Task, Condition]
    best_by_cond = sorted_df.groupby(group_cols, as_index=False).first()
    
    # Best overall per Task
    if "Task" in combined_df.columns:
        best_by_task = sorted_df.groupby("Task", as_index=False).first()
    else:
        best_by_task = best_by_cond.copy()

    # 5. Display selection summary
    print("\n" + "="*80)
    print("PEAK PERFORMANCE SUMMARY BY [TASK, CONDITION]")
    print("="*80)
    display_cols = [c for c in ["Task", "Condition", "Window", "Band", "Feature_Mode", "Model", "AUC_mean", "Accuracy_mean"] if c in best_by_cond.columns]
    print(best_by_cond[display_cols].to_string(index=False))

    # 6. Save output CSV files
    out_best_cond_path = os.path.join(OUTPUT_DIR, "multiclass_best_results_all_conditions.csv")
    out_best_task_path = os.path.join(OUTPUT_DIR, "multiclass_best_overall_by_task.csv")
    
    best_by_cond.to_csv(out_best_cond_path, index=False)
    best_by_task.to_csv(out_best_task_path, index=False)
    
    print(f"\n✓ Saved peak models per [Task, Condition] to: '{out_best_cond_path}'")
    print(f"✓ Saved peak models per Task to:             '{out_best_task_path}'")
    print("="*80)

if __name__ == "__main__":
    main()
