#!/usr/bin/env python3
"""
07_permutation_test_best_models.py
---------------------------------
Evaluates statistical significance of peak multiclass & multi-task classification
models by running permutation tests (default: 1000 iterations).

Features:
- Dynamically parses dataset filenames formatted as 'dataset_{condition}_{start}_{end}.csv'
  (e.g., 'dataset_gu3_400_800.csv', 'dataset_gu2_0_300.csv').
- Reads optimal configurations from 'multiclass_best_results_all_conditions.csv' or
  'multiclass_best_overall_by_task.csv' generated by Step 06.5.
- Evaluates feature modes (FC, PSD, PSD_FC) and active classification targets:
  Age_Group, Language_Tonal, Language, Age_Child_Language_Tonal, Age_Child_Language.
"""

import os
import sys
import re
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
import warnings
warnings.filterwarnings('ignore')
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
if BASE_DIR.name == "scripts":
    BASE_DIR = BASE_DIR.parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(exist_ok=True)
INPUT_DIR = OUTPUT_DIR
base_path = Path(DATA_DIR).expanduser()

N_PERMUTATIONS = 1000

def resolve_dataset_filename(input_dir, condition, window_str):
    """
    Resolves dataset filename matching formats like 'dataset_gu3_400_800.csv'.
    """
    # Clean window string: '400-800ms' -> '400_800', '0-300ms' -> '0_300'
    clean_win = str(window_str).replace("ms", "").replace("-", "_").replace(" ", "").strip()
    
    candidates = [
        f"dataset_{condition}_{clean_win}.csv",       # e.g., dataset_gu3_400_800.csv
        f"dataset_{condition}_{window_str}.csv",     # e.g., dataset_gu3_400-800ms.csv
        f"dataset_{condition}.csv"                    # fallback default
    ]
    
    for candidate in candidates:
        full_path = os.path.join(input_dir, candidate)
        if os.path.exists(full_path):
            return full_path
            
    # Default to first candidate path if none currently exist
    return os.path.join(input_dir, candidates[0])

def filter_features_by_mode(df, band, feature_mode):
    """Selects columns based on band and feature mode (FC, PSD, PSD_FC)."""
    all_bands = ["delta", "theta", "alpha", "beta", "highbeta", "gamma"]
    
    if band == "all":
        band_cols = [c for c in df.columns if any(c.startswith(b + "_") for b in all_bands)]
    else:
        band_cols = [c for c in df.columns if c.startswith(band + "_")]
        
    if feature_mode == "FC":
        return [c for c in band_cols if not ("psd" in c.lower() or "power" in c.lower())]
    elif feature_mode == "PSD":
        return [c for c in band_cols if ("psd" in c.lower() or "power" in c.lower())]
    else:  # PSD_FC or default
        return band_cols

def evaluate_model_cv(X, y, model_name, model, classes):
    """Runs 5-Fold Stratified CV on shuffled labels to compute null macro AUC."""
    n_samples = len(y)
    min_class_samples = pd.Series(y).value_counts().min()
    n_splits = min(5, min_class_samples) if min_class_samples >= 2 else 2
    
    if min_class_samples < 2:
        return 0.5  # Degenerate case fallback
        
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    fold_aucs = []
    
    for train_idx, test_idx in skf.split(X, y):
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]
        
        if model_name in ["Linear SVM", "Elastic Net"]:
            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_test_scaled = scaler.transform(X_test)
        else:
            X_train_scaled = X_train
            X_test_scaled = X_test
            
        model.fit(X_train_scaled, y_train)
        y_proba = model.predict_proba(X_test_scaled)
        
        # Determine classes present in fold
        fold_classes = sorted(list(np.unique(y_test)))
        if len(fold_classes) < 2:
            continue
            
        if len(classes) == 2:
            # Binary classification AUC
            pos_label = classes[1]
            if len(model.classes_) == 2 and pos_label in model.classes_:
                pos_idx = list(model.classes_).index(pos_label)
                score = y_proba[:, pos_idx]
            else:
                score = y_proba[:, 1] if y_proba.shape[1] > 1 else y_proba[:, 0]
            auc = roc_auc_score(y_test, score)
        else:
            # Multiclass OvR macro AUC
            auc = roc_auc_score(y_test, y_proba, multi_class='ovr', average='macro', labels=classes)
            
        fold_aucs.append(auc)
        
    return np.mean(fold_aucs) if fold_aucs else 0.5

def get_target_labels(df, task_name):
    """Maps task names to DataFrame target columns."""
    task_col_map = {
        "Age_Group": "age_group",
        "Language_Tonal": "lang_tonal",
        "Language": "lang",
        "Age_Child_Language_Tonal": "age_child_lang_tonal",
        "Age_Child_Language": "age_child_lang"
    }
    
    col = task_col_map.get(task_name, None)
    if col and col in df.columns:
        return df[col].values
        
    # Column resolution fallbacks
    for c in [col, task_name.lower(), "age_group", "target"]:
        if c and c in df.columns:
            return df[c].values
            
    return None

def main():
    global N_PERMUTATIONS
    if len(sys.argv) > 1:
        try:
            N_PERMUTATIONS = int(sys.argv[1])
        except ValueError:
            pass
            
    print(f"=== Step 3: Multiclass & Multi-Task Permutation Testing ({N_PERMUTATIONS} iterations) ===")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    best_results_path = os.path.join(OUTPUT_DIR, "multiclass_best_results_all_conditions.csv")
    if not os.path.exists(best_results_path):
        best_results_path = os.path.join(OUTPUT_DIR, "multiclass_best_overall_by_task.csv")
        
    if os.path.exists(best_results_path):
        best_df = pd.read_csv(best_results_path)
        print(f"Loaded target models to evaluate from '{best_results_path}'")
    else:
        print("Warning: No precomputed best results file found. Using default peak baseline configurations.")
        best_df = pd.DataFrame([
            {"Task": "Age_Group", "Condition": "gu2", "Window": "0-800ms", "Band": "beta", "Feature_Mode": "PSD", "Model": "Elastic Net", "AUC_mean": 0.7240},
            {"Task": "Language_Tonal", "Condition": "gu2", "Window": "400-800ms", "Band": "delta", "Feature_Mode": "FC", "Model": "Random Forest", "AUC_mean": 0.7010},
            {"Task": "Language", "Condition": "gu2", "Window": "0-300ms", "Band": "all", "Feature_Mode": "FC", "Model": "Linear SVM", "AUC_mean": 0.6490},
            {"Task": "Age_Child_Language_Tonal", "Condition": "gu1", "Window": "300-600ms", "Band": "delta", "Feature_Mode": "PSD", "Model": "Random Forest", "AUC_mean": 0.6440},
            {"Task": "Age_Child_Language", "Condition": "gu3", "Window": "300-600ms", "Band": "delta", "Feature_Mode": "PSD", "Model": "Random Forest", "AUC_mean": 0.6510}
        ])

    model_templates = {
        "Linear SVM": SVC(kernel="linear", class_weight="balanced", probability=True, random_state=42),
        "Random Forest": RandomForestClassifier(n_estimators=500, max_features="sqrt", class_weight="balanced", random_state=42),
        "Elastic Net": LogisticRegression(penalty="elasticnet", solver="saga", l1_ratio=0.5, C=1.0, class_weight="balanced", max_iter=20000, random_state=42)
    }

    permutation_results = []

    for idx, row in best_df.iterrows():
        task = row.get("Task", "Age_Group")
        condition = row.get("Condition", "gu1")
        window_str = row.get("Window", "0-800ms")
        band = row.get("Band", "delta")
        feature_mode = row.get("Feature_Mode", "PSD_FC")
        model_name = row.get("Model", "Random Forest")
        true_auc = float(row.get("AUC_mean", 0.5))

        file_path = resolve_dataset_filename(INPUT_DIR, condition, window_str)
        if not os.path.exists(file_path):
            print(f"Warning: File '{file_path}' not found for Task '{task}'. Skipping.")
            continue

        print(f"\nRunning Permutations ({N_PERMUTATIONS}) for Task: {task:25} | Cond: {condition} | Window: {window_str:9} | Band: {band:8} | Mode: {feature_mode:6} | Model: {model_name} (True AUC = {true_auc:.4f})")
        df = pd.read_csv(file_path)
        df = df.drop_duplicates(subset=["participant_id"]) if "participant_id" in df.columns else df

        y = get_target_labels(df, task)
        if y is None:
            print(f"  Warning: Target labels for '{task}' not found in DataFrame. Skipping.")
            continue

        classes = sorted(list(np.unique(y)))
        feature_cols = filter_features_by_mode(df, band, feature_mode)
        if not feature_cols:
            print(f"  Warning: No features found matching band '{band}' and mode '{feature_mode}'. Skipping.")
            continue

        X = df[feature_cols].values
        model = model_templates.get(model_name, model_templates["Random Forest"])

        shuffled_aucs = []
        np.random.seed(42)

        for i in range(N_PERMUTATIONS):
            y_shuffled = np.random.permutation(y)
            perm_auc = evaluate_model_cv(X, y_shuffled, model_name, model, classes)
            shuffled_aucs.append(perm_auc)

            if (i + 1) % 200 == 0 or (i + 1) == N_PERMUTATIONS:
                print(f"  Completed {i + 1}/{N_PERMUTATIONS} iterations...")

        shuffled_aucs = np.array(shuffled_aucs)
        num_exceed = sum(1 for perm_auc in shuffled_aucs if perm_auc >= true_auc)
        p_value = (num_exceed + 1) / (N_PERMUTATIONS + 1)

        sig_str = "p < 0.001 ***" if p_value < 0.001 else (f"p = {p_value:.4f} *" if p_value < 0.05 else f"p = {p_value:.4f} (n.s.)")
        print(f"  âœ“ Empirical p-value: {sig_str} [Exceeded {num_exceed}/{N_PERMUTATIONS} times, Null Mean = {shuffled_aucs.mean():.4f}]")

        permutation_results.append({
            "Task": task,
            "Condition": condition,
            "Window": window_str,
            "Band": band,
            "Feature_Mode": feature_mode,
            "Model": model_name,
            "True_AUC": true_auc,
            "Permutation_P_Value": p_value,
            "Mean_Null_AUC": shuffled_aucs.mean(),
            "Max_Null_AUC": shuffled_aucs.max()
        })

        # Save individual null distribution
        safe_task = str(task).replace(" ", "_")
        dist_df = pd.DataFrame({"shuffled_auc": shuffled_aucs})
        dist_path = os.path.join(OUTPUT_DIR, f"permutation_distribution_{safe_task}_{condition}_{window_str}_{band}_{model_name.replace(' ', '')}.csv")
        dist_df.to_csv(dist_path, index=False)

    summary_df = pd.DataFrame(permutation_results)
    summary_path = os.path.join(OUTPUT_DIR, "multiclass_permutation_results.csv")
    summary_df.to_csv(summary_path, index=False)
    print(f"\nâœ“ Saved full permutation results summary to: '{summary_path}'")

if __name__ == "__main__":
    main()